{{- if .Values.jobs.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if .Values.jobs.migrate.jobName }}
  name: {{ .Values.jobs.migrate.jobName }}
  {{- else }}
  name: {{ template "erpnext.fullname" . }}-migrate-{{ now | date "20060102150405" }}
  {{- end }}
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
  {{- with .Values.jobs.migrate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .Values.jobs.migrate.backoffLimit }}
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "erpnext.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bash", "-c"]
        args:
          - >
            {{- if eq .Values.jobs.migrate.mode "single" }}
            bench --site {{ .Values.jobs.migrate.siteName }} set-maintenance-mode on;
            bench --site {{ .Values.jobs.migrate.siteName }} migrate{{ if .Values.jobs.migrate.skipFailing }} --skip-failing{{ end }};
            bench --site {{ .Values.jobs.migrate.siteName }} set-maintenance-mode off;
            {{- else if eq .Values.jobs.migrate.mode "all" }}
            for site_dir in sites/*; do
              if [ -d "$site_dir" ] && [ -f "$site_dir/site_config.json" ]; then
                site=$(basename "$site_dir");
                bench --site $site set-maintenance-mode on;
                bench --site $site migrate{{ if .Values.jobs.migrate.skipFailing }} --skip-failing{{ end }};
                bench --site $site set-maintenance-mode off;
              fi;
            done
            {{- else if eq .Values.jobs.migrate.mode "regex" }}
            for site_dir in sites/*; do
              if [ -d "$site_dir" ] && [ -f "$site_dir/site_config.json" ]; then
                site=$(basename "$site_dir");
                if [[ $site =~ "{{ .Values.jobs.migrate.sitesRegex }}" ]]; then
                  bench --site $site set-maintenance-mode on;
                  bench --site $site migrate{{ if .Values.jobs.migrate.skipFailing }} --skip-failing{{ end }};
                  bench --site $site set-maintenance-mode off;
                fi;
              fi;
            done
            {{- else if eq .Values.jobs.migrate.mode "list" }}
            {{- range .Values.jobs.migrate.sites }}
            bench --site {{ . }} set-maintenance-mode on;
            bench --site {{ . }} migrate{{ if $.Values.jobs.migrate.skipFailing }} --skip-failing{{ end }};
            bench --site {{ . }} set-maintenance-mode off;
            {{- end }}
            {{- end }}
            {{- if .Values.jobs.migrate.enableCacheFlush }}
            python3 -c "
            import json
            import redis
            try:
                with open('sites/common_site_config.json') as f:
                    config = json.load(f)
                redis_url = config.get('redis_cache')
                if redis_url:
                    r = redis.from_url(redis_url)
                    r.flushall()
                    print('Redis cache flushed')
                else:
                    print('No redis_cache in config')
            except Exception as e:
                print(f'Error flushing Redis: {e}')
            "
            {{- end }}
        resources:
          {{- toYaml .Values.jobs.migrate.resources | nindent 10 }}
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 10 }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      restartPolicy: Never
      volumes:
        - name: sites-dir
          {{- if .Values.persistence.worker.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.worker.existingClaim }}
            claimName: {{ .Values.persistence.worker.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.logs.existingClaim }}
            claimName: {{ .Values.persistence.logs.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}-logs
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.jobs.migrate.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.migrate.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.migrate.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
