{{- if .Values.jobs.backup.enabled }}
{{- if .Values.jobs.backup.schedule }}
apiVersion: batch/v1
kind: CronJob
metadata:
  {{- if .Values.jobs.backup.jobName }}
  name: {{ .Values.jobs.backup.jobName }}
  {{- else }}
  name: {{ template "erpnext.fullname" . }}-backup
  {{- end }}
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.jobs.backup.schedule }}"
  {{- if .Values.jobs.backup.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.jobs.backup.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.jobs.backup.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.jobs.backup.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.jobs.backup.backoffLimit }}
      template:
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ template "erpnext.serviceAccountName" $ }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          containers:
          - name: backup
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["bash", "-c"]
            args:
              - |
                {{- if eq .Values.jobs.backup.mode "single" }}
                  # single site comes from env variable
                  set -e
                  SITE=$SITE_NAME
                  SAFE_SITE=$(echo "$SITE" | tr '.' '_')
                  TIMESTAMP=$(date +%d_%m_%Y-%H_%M_%S)
                  BACKUP_DIR="{{ .Values.jobs.backup.backupPath }}/$SAFE_SITE/${TIMESTAMP}-${SAFE_SITE}"
                  mkdir -p "$BACKUP_DIR"
                  bench --site=$SITE{{- if .Values.jobs.backup.withFiles }} backup --with-files{{- else }} backup{{- end }}{{- if .Values.jobs.backup.compress }} --compress{{- end }}{{- if .Values.jobs.backup.backupPath }} --backup-path="$BACKUP_DIR"{{- end }};
                  EXIT=$?;
                  {{- if (gt ($.Values.jobs.backup.olderThan | int) 0) }}
                  if [ $EXIT -eq 0 ]; then
                    find "{{ .Values.jobs.backup.backupPath }}/$SAFE_SITE" -maxdepth 1 -type d -mmin +{{ .Values.jobs.backup.olderThan }} -exec rm -rf {} \;
                  fi;
                  {{- end }}
                {{- else if eq .Values.jobs.backup.mode "all" }}
                  # backup all sites
                  set -e
                  for d in /home/frappe/frappe-bench/sites/*; do
                    # only consider directories that look like Frappe sites
                    if [ -d "$d" ] && [ -f "$d/site_config.json" ]; then
                      SITE=$(basename "$d");
                      SAFE_SITE=$(echo "$SITE" | tr '.' '_')
                      TIMESTAMP=$(date +%d_%m_%Y-%H_%M_%S)
                      BACKUP_DIR="{{ .Values.jobs.backup.backupPath }}/$SAFE_SITE/${TIMESTAMP}-${SAFE_SITE}"
                      mkdir -p "$BACKUP_DIR"
                      bench --site=$SITE{{- if .Values.jobs.backup.withFiles }} backup --with-files{{- else }} backup{{- end }}{{- if .Values.jobs.backup.compress }} --compress{{- end }}{{- if .Values.jobs.backup.backupPath }} --backup-path="$BACKUP_DIR"{{- end }};
                      EXIT=$?;
                      {{- if (gt ($.Values.jobs.backup.olderThan | int) 0) }}
                      if [ $EXIT -eq 0 ]; then
                        find "{{ .Values.jobs.backup.backupPath }}/$SAFE_SITE" -maxdepth 1 -type d -mmin +{{ .Values.jobs.backup.olderThan }} -exec rm -rf {} \;
                      fi;
                      {{- end }}
                    fi;
                  done
                {{- else if eq .Values.jobs.backup.mode "regex" }}
                # backup sites based on regex expression
                  set -e
                  for d in /home/frappe/frappe-bench/sites/*; do
                    if [ -d "$d" ] && [ -f "$d/site_config.json" ]; then
                      SITE=$(basename "$d");
                      if echo "$SITE" | grep -E '{{ .Values.jobs.backup.sitesRegex }}' >/dev/null; then
                        SAFE_SITE=$(echo "$SITE" | tr '.' '_')
                        TIMESTAMP=$(date +%d_%m_%Y-%H_%M_%S)
                        BACKUP_DIR="{{ .Values.jobs.backup.backupPath }}/$SAFE_SITE/${TIMESTAMP}-${SAFE_SITE}"
                        mkdir -p "$BACKUP_DIR"
                        bench --site=$SITE{{- if .Values.jobs.backup.withFiles }} backup --with-files{{- else }} backup{{- end }}{{- if .Values.jobs.backup.compress }} --compress{{- end }}{{- if .Values.jobs.backup.backupPath }} --backup-path="$BACKUP_DIR"{{- end }};
                      fi;
                    fi;
                    EXIT=$?;
                    {{- if (gt ($.Values.jobs.backup.olderThan | int) 0) }}
                    if [ $EXIT -eq 0 ]; then
                      find "{{ .Values.jobs.backup.backupPath }}/$SAFE_SITE" -maxdepth 1 -type d -mmin +{{ .Values.jobs.backup.olderThan }} -exec rm -rf {} \;
                    fi;
                    {{- end }}
                  done
                {{- else if eq .Values.jobs.backup.mode "list" }}
                # backup sites based on list
                  set -e
                  for SITE in {{- range $s := .Values.jobs.backup.sites }}'{{ $s }}' {{- end }}; do SITE=${SITE//\'/}; bench --site=$SITE{{- if .Values.jobs.backup.withFiles }} backup --with-files{{- else }} backup{{- end }}{{- if .Values.jobs.backup.compress }} --compress{{- end }}{{- if .Values.jobs.backup.backupPath }} --backup-path={{ .Values.jobs.backup.backupPath }}{{- end }};
                  EXIT=$?;
                  {{- if (gt ($.Values.jobs.backup.olderThan | int) 0) }}
                  if [ $EXIT -eq 0 ]; then
                    find "{{ .Values.jobs.backup.backupPath }}/$SAFE_SITE" -maxdepth 1 -type d -mmin +{{ .Values.jobs.backup.olderThan }} -exec rm -rf {} \;
                  fi;
                  {{- end }}
                  done
                {{- else }}
                  echo "Invalid backup mode: {{ .Values.jobs.backup.mode }}" && exit 1
                {{- end }}
          {{- if eq .Values.jobs.backup.mode "single" }}
            env:
              - name: "SITE_NAME"
                value: "{{ .Values.jobs.backup.siteName }}"
          {{- end }}
            resources:
              {{- toYaml .Values.jobs.backup.resources | nindent 14 }}
            securityContext:
              {{- toYaml $.Values.securityContext | nindent 14 }}
            volumeMounts:
              - name: sites-dir
                mountPath: /home/frappe/frappe-bench/sites
              - name: logs
                mountPath: /home/frappe/frappe-bench/logs
          restartPolicy: Never
          volumes:
            - name: sites-dir
              {{- if .Values.persistence.worker.enabled }}
              persistentVolumeClaim:
                {{- if .Values.persistence.worker.existingClaim }}
                claimName: {{ .Values.persistence.worker.existingClaim }}
                {{- else }}
                claimName: {{ template "erpnext.fullname" . }}
                {{- end }}
                readOnly: false
              {{- else }}
              emptyDir: {}
              {{- end }}
            - name: logs
              {{- if .Values.persistence.logs.enabled }}
              persistentVolumeClaim:
                {{- if .Values.persistence.logs.existingClaim }}
                claimName: {{ .Values.persistence.logs.existingClaim }}
                {{- else }}
                claimName: {{ template "erpnext.fullname" . }}-logs
                {{- end }}
                readOnly: false
              {{- else }}
              emptyDir: {}
              {{- end }}
          {{- with .Values.jobs.backup.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jobs.backup.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jobs.backup.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- else }}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if .Values.jobs.backup.jobName }}
  name: {{ .Values.jobs.backup.jobName }}
  {{- else }}
  name: {{ template "erpnext.fullname" . }}-backup-{{ now | date "20060102150405" }}
  {{- end }}
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.jobs.backup.backoffLimit }}
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "erpnext.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
      - name: backup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bash", "-c"]
        args:
          - >
            {{- if eq .Values.jobs.backup.mode "single" }}
              bench --site=$(SITE_NAME){{- if .Values.jobs.backup.withFiles }} backup --with-files;{{- else }} backup;{{- end }}
            {{- else if eq .Values.jobs.backup.mode "all" }}
              for d in /home/frappe/frappe-bench/sites/*; do SITE=$(basename "$d"); bench --site=$SITE{{- if .Values.jobs.backup.withFiles }} backup --with-files;{{- else }} backup;{{- end }}; done
            {{- else if eq .Values.jobs.backup.mode "regex" }}
              for d in /home/frappe/frappe-bench/sites/*; do SITE=$(basename "$d"); if echo "$SITE" | grep -E '{{ .Values.jobs.backup.sitesRegex }}' >/dev/null; then bench --site=$SITE{{- if .Values.jobs.backup.withFiles }} backup --with-files;{{- else }} backup;{{- end }}; fi; done
            {{- else if eq .Values.jobs.backup.mode "list" }}
              for SITE in {{- range $s := .Values.jobs.backup.sites }}'{{ $s }}' {{- end }}; do SITE=${SITE//\'/}; bench --site=$SITE{{- if .Values.jobs.backup.withFiles }} backup --with-files;{{- else }} backup;{{- end }}; done
            {{- else }}
              echo "Invalid backup mode: {{ .Values.jobs.backup.mode }}" && exit 1
            {{- end }}
        env:
          - name: "SITE_NAME"
            value: "{{ .Values.jobs.backup.siteName }}"
        resources:
          {{- toYaml .Values.jobs.backup.resources | nindent 10 }}
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 10 }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      restartPolicy: Never
      volumes:
        - name: sites-dir
          {{- if .Values.persistence.worker.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.worker.existingClaim }}
            claimName: {{ .Values.persistence.worker.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.logs.existingClaim }}
            claimName: {{ .Values.persistence.logs.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}-logs
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.jobs.backup.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.backup.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.backup.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
