{{- if and .Values.persistence.worker.enabled (not .Values.persistence.worker.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{ template "erpnext.name" . }}
    chart: {{ template "erpnext.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.persistence.worker.annotations | nindent 4 }}
  name: {{ template "erpnext.fullname" . }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.worker.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.worker.size | quote }}
  {{- if not .Values.persistence.worker.existingPV }}
  storageClassName: {{ required "A valid persistence.worker.storageClass entry required!" .Values.persistence.worker.storageClass }}
  {{- end }}
  {{- if .Values.persistence.worker.existingPV }}
  volumeName: {{ .Values.persistence.worker.existingPV | quote }}
  {{- end }}
{{- end }}
